### ISSUE TITLE
Error trying to test an ember-cli addon

### ISSUE THREAD

**Issue by Gaurav0** [switchfly/ember-cli-mocha#66]
Using master, I get the following error when I run ember test in an addon directory:

Cannot read property 'jshintrc' of undefined

I tried fixing this in my fork here: https://github.com/Gaurav0/ember-cli-mocha/commit/c3020151911c1e949f429d9b2fe0e47b211bef97

and then I get this error:

It looks like you're not on ember-cli 1.13, which includes ember-cli-htmlbars-inline-precompile by default. Please run: ember install ember-cli-htmlbars-inline-precompile.

If I follow those instructions then I get:

Cannot find module 'handlebars'
Error: Cannot find module 'handlebars'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/gmunjal/code/web/ember/hs-lookup/bower_components/ember/ember-template-compiler.js:34:16
    at Object.<anonymous> (/Users/gmunjal/code/web/ember/hs-lookup/bower_components/ember/ember-template-compiler.js:332:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

I am using ember-cli 0.2.7 with Ember 1.8.1

**Comment by Gaurav0** [comment]
Solved the issue. Needed to bring in handlebars as a dependency in package.json as it is being required from a node process.
