### ISSUE TITLE
dependancy on ember-cli-shim

### ISSUE THREAD

**Issue by klclee** [switchfly/ember-cli-mocha#72]
When installing this I am getting the error ```Package ember-cli-shims not found``` below is the full log.

```
─$ ember install ember-cli-mocha                                                                                                                                                                    1 ↵
version: 1.13.1
Installed packages for tooling via npm.
installing ember-cli-mocha
  identical tests/test-helper.js
Installing browser packages via Bower...
  not-cached git://github.com/switchfly/ember-mocha-builds.git#~0.8.0
  cached git://github.com/ember-cli/ember-cli-test-loader.git#0.1.3
  resolved git://github.com/switchfly/ember-mocha-builds.git#0.8.0
Package ember-cli-shims not found
Error: Package ember-cli-shims not found
    at createError (/Users/charlie/Development/shippingClient/node_modules/ember-cli/node_modules/bower/lib/util/createError.js:4:15)
    at /Users/charlie/Development/shippingClient/node_modules/ember-cli/node_modules/bower/lib/core/resolverFactory.js:143:27
    at _fulfilled (/Users/charlie/Development/shippingClient/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/charlie/Development/shippingClient/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/charlie/Development/shippingClient/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:796:13)
    at /Users/charlie/Development/shippingClient/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:604:44
    at runSingle (/Users/charlie/Development/shippingClient/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:137:13)
    at flush (/Users/charlie/Development/shippingClient/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:355:11)
```

**Comment by dylanfoster** [comment]
Same issue here, and I can verify that indeed, ember-cli-shims IS installed

**Comment by blimmer** [comment]
This was a temporary problem that was resolved. This issue can be closed.
